server:
  port: ${SERVER_PORT:8088}
spring:
  application:
    name: notification-service
  mail:
    host: ${SMTP_HOST:smtp_host}
    username: ${SMTP_USERNAME:smtp_username}
    password: ${SMTP_PASSWORD:smtp_password}
    port: ${SMTP_PORT:587}
    properties:
      mail:
        smtp:
          auth: 'true'
          starttls:
            enable: 'true'
            required: 'true'
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

notification:
  templates:
    user-registration:
      to: ${USER_REG_TO:bittu.kumar@betoo.co.in,cixadem596@advarm.com}
      cc: ${USER_REG_CC:cixadem596@advarm.com}

logging:
  level:
    com.bqp.bqphy.notificationservice: DEBUG

service:
  IDENTITY_SERVICE: ${IDENTITY_SERVICE:http://identity-service:8080}